### ISSUE TITLE
ICMP responder connection breaks after NSM upgrade

### ISSUE THREAD

**Issue by rpiceage** [networkservicemesh/cmd-nse-icmp-responder#287] opened 2021-08-24 12:42 UTC
We would like to use the nse-icmp-responder and nsc endpoint kernel2kernel example for NSM upgrade tests. Our tests fail, the connection is OK before 'helm upgrade', but after the upgrade the connection between NSE and NSC is usually lost. (NSE and NSC are not upgraded, only the NSM infrastructure below them.) The behavior is not entirely deterministic, in some cases multiple interfaces appear in the NSE after the upgrade with conflicting IP addresses.

For example:

Before the upgrade (ping OK):

NSC:
```
kubectl exec -n nsm endpoint-nsc-7789d64bcc-wc7p5 -- ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
4: eth0@if194402: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1430 qdisc noqueue state UP 
    link/ether 66:82:28:2c:47:4c brd ff:ff:ff:ff:ff:ff
    inet 192.168.215.162/32 scope global eth0
       valid_lft forever preferred_lft forever
194404: nsm-1@if194403: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 9000 qdisc noqueue state UP qlen 1000
    link/ether e6:0b:fb:1a:cf:54 brd ff:ff:ff:ff:ff:ff
    inet 172.16.1.97/32 scope global nsm-1
       valid_lft forever preferred_lft forever
    inet6 fe80::e40b:fbff:fe1a:cf54/64 scope link 
       valid_lft forever preferred_lft forever
```

NSE:
```
kubectl exec -n nsm endpoint-nse-5bd8b66987-bwj4l -- ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
4: eth0@if194401: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1430 qdisc noqueue state UP 
    link/ether 6e:b7:f4:fc:1f:88 brd ff:ff:ff:ff:ff:ff
    inet 192.168.215.142/32 scope global eth0
       valid_lft forever preferred_lft forever
194406: icmp-respo-f913@if194405: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 9000 qdisc noqueue state UP qlen 1000
    link/ether fa:3c:f2:96:2d:f2 brd ff:ff:ff:ff:ff:ff
    inet 172.16.1.96/32 scope global icmp-respo-f913
       valid_lft forever preferred_lft forever
    inet6 fe80::f83c:f2ff:fe96:2df2/64 scope link 
       valid_lft forever preferred_lft forever
```

After the upgrade (connection lost):

NSC:
```
kubectl exec -n nsm endpoint-nsc-7789d64bcc-wc7p5 -- ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
4: eth0@if194402: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1430 qdisc noqueue state UP 
    link/ether 66:82:28:2c:47:4c brd ff:ff:ff:ff:ff:ff
    inet 192.168.215.162/32 scope global eth0
       valid_lft forever preferred_lft forever
194409: nsm-1@if194408: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 9000 qdisc noqueue state UP qlen 1000
    link/ether b6:9e:d6:9b:ec:b3 brd ff:ff:ff:ff:ff:ff
    inet 172.16.1.97/32 scope global nsm-1
       valid_lft forever preferred_lft forever
    inet 172.16.1.99/32 scope global nsm-1
       valid_lft forever preferred_lft forever
    inet6 fe80::b49e:d6ff:fe9b:ecb3/64 scope link 
       valid_lft forever preferred_lft forever
```

NSE:
```
kubectl exec -n nsm endpoint-nse-5bd8b66987-bwj4l -- ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
4: eth0@if194401: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1430 qdisc noqueue state UP 
    link/ether 6e:b7:f4:fc:1f:88 brd ff:ff:ff:ff:ff:ff
    inet 192.168.215.142/32 scope global eth0
       valid_lft forever preferred_lft forever
194406: icmp-respo-f913@if194405: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 9000 qdisc noqueue state UP qlen 1000
    link/ether fa:3c:f2:96:2d:f2 brd ff:ff:ff:ff:ff:ff
    inet 172.16.1.96/32 scope global icmp-respo-f913
       valid_lft forever preferred_lft forever
    inet6 fe80::f83c:f2ff:fe96:2df2/64 scope link 
       valid_lft forever preferred_lft forever
194411: icmp-respo-57e2@if194410: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 9000 qdisc noqueue state UP qlen 1000
    link/ether de:61:0c:9d:e4:d3 brd ff:ff:ff:ff:ff:ff
    inet 172.16.1.96/32 scope global icmp-respo-57e2
       valid_lft forever preferred_lft forever
    inet 172.16.1.98/32 scope global icmp-respo-57e2
       valid_lft forever preferred_lft forever
    inet6 fe80::dc61:cff:fe9d:e4d3/64 scope link 
       valid_lft forever preferred_lft forever
```

After a minute:

NSC:
```
kubectl exec -n nsm endpoint-nsc-7789d64bcc-wc7p5 -- ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
4: eth0@if194402: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1430 qdisc noqueue state UP 
    link/ether 66:82:28:2c:47:4c brd ff:ff:ff:ff:ff:ff
    inet 192.168.215.162/32 scope global eth0
       valid_lft forever preferred_lft forever
194414: nsm-1@if194413: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 9000 qdisc noqueue state UP qlen 1000
    link/ether fe:fe:22:ea:b5:88 brd ff:ff:ff:ff:ff:ff
    inet 172.16.1.97/32 scope global nsm-1
       valid_lft forever preferred_lft forever
    inet 172.16.1.101/32 scope global nsm-1
       valid_lft forever preferred_lft forever
    inet6 fe80::fcfe:22ff:feea:b588/64 scope link 
       valid_lft forever preferred_lft forever
```

NSE:
```
kubectl exec -n nsm endpoint-nse-5bd8b66987-bwj4l -- ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
4: eth0@if194401: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1430 qdisc noqueue state UP 
    link/ether 6e:b7:f4:fc:1f:88 brd ff:ff:ff:ff:ff:ff
    inet 192.168.215.142/32 scope global eth0
       valid_lft forever preferred_lft forever
194406: icmp-respo-f913@if194405: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 9000 qdisc noqueue state UP qlen 1000
    link/ether fa:3c:f2:96:2d:f2 brd ff:ff:ff:ff:ff:ff
    inet 172.16.1.96/32 scope global icmp-respo-f913
       valid_lft forever preferred_lft forever
    inet6 fe80::f83c:f2ff:fe96:2df2/64 scope link 
       valid_lft forever preferred_lft forever
194411: icmp-respo-57e2@if194410: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 9000 qdisc noqueue state UP qlen 1000
    link/ether de:61:0c:9d:e4:d3 brd ff:ff:ff:ff:ff:ff
    inet 172.16.1.96/32 scope global icmp-respo-57e2
       valid_lft forever preferred_lft forever
    inet 172.16.1.98/32 scope global icmp-respo-57e2
       valid_lft forever preferred_lft forever
    inet6 fe80::dc61:cff:fe9d:e4d3/64 scope link 
       valid_lft forever preferred_lft forever
194416: icmp-respo-6c1c@if194415: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 9000 qdisc noqueue state UP qlen 1000
    link/ether e2:c0:69:72:63:60 brd ff:ff:ff:ff:ff:ff
    inet 172.16.1.96/32 scope global icmp-respo-6c1c
       valid_lft forever preferred_lft forever
    inet 172.16.1.100/32 scope global icmp-respo-6c1c
       valid_lft forever preferred_lft forever
    inet6 fe80::e0c0:69ff:fe72:6360/64 scope link 
       valid_lft forever preferred_lft forever
```

Images used:
- cmd-nse-icmp-responder 1.0.0
- cmd-nsc 1.0.0
- nsmgr 1.0.0
- registry-memory 1.0.0
- forwarder-vpp 1.0.0

kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"ec2760d6d916781de466541a6babb4309766c995", GitTreeState:"clean", BuildDate:"2021-02-27T17:18:03Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

helm version
version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"clean", GoVersion:"go1.16.3"}

**Comment by rpiceage** [comment] 2021-08-24 13:00
[endpoint-nsc-7789d64bcc-wc7p5-endpoint-nsc.txt](https://github.com/networkservicemesh/cmd-nse-icmp-responder/files/7039297/endpoint-nsc-7789d64bcc-wc7p5-endpoint-nsc.txt)

**Comment by rpiceage** [comment] 2021-08-24 13:01
[nsmgr-kqlr6-nsmgr.txt](https://github.com/networkservicemesh/cmd-nse-icmp-responder/files/7039319/nsmgr-kqlr6-nsmgr.txt)
[nsm-registry-6f7c9d7bff-zmscp-nsm-registry.txt](https://github.com/networkservicemesh/cmd-nse-icmp-responder/files/7039322/nsm-registry-6f7c9d7bff-zmscp-nsm-registry.txt)

**Comment by denis-tingaikin** [comment] 2021-09-21 15:27
@rpiceage Could you also attach your steps one by one to reproduce this locally?

**Comment by rpiceage** [comment] 2021-09-22 13:07
Hi, I could reproduce some error without helm upgrade and helm chart. It's not the same setup, but our test would be very hard to reproduce locally. Maybe this will help:
I set up the Kernel2Kernel example for v1.0.0, verified the ping and extra interface in NSC:
`kubectl exec -it -n ns-9jv7p nsc-kernel-cd7b5657c-8gc8x -- sh
/ # ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
3: eth0@if4: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP 
    link/ether 5e:d4:48:21:c8:e4 brd ff:ff:ff:ff:ff:ff
    inet 10.244.3.4/24 brd 10.244.3.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::5cd4:48ff:fe21:c8e4/64 scope link 
       valid_lft forever preferred_lft forever
7: nsm-1@if6: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 9000 qdisc noqueue state UP qlen 1000
    link/ether 0a:d9:85:06:c8:01 brd ff:ff:ff:ff:ff:ff
    inet 169.254.0.1/32 scope global nsm-1
       valid_lft forever preferred_lft forever
    inet6 fe80::8d9:85ff:fe06:c801/64 scope link 
       valid_lft forever preferred_lft forever
`
After that I pulled, re-tagged the nsmgr image, and pushed to my own registry.
Changed the image in the nsmgr.yaml to the re-tagged one.
Re-run the same command:
`kubectl apply -k .`
A rolling upgrade was performed for thee nsmgr. After that the extra interface disappeared from the NSC:
`kubectl exec -it -n ns-9jv7p nsc-kernel-cd7b5657c-8gc8x -- sh
/ # ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
3: eth0@if4: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP 
    link/ether 5e:d4:48:21:c8:e4 brd ff:ff:ff:ff:ff:ff
    inet 10.244.3.4/24 brd 10.244.3.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::5cd4:48ff:fe21:c8e4/64 scope link 
       valid_lft forever preferred_lft forever
`
And a lot of error message in the logs.
Hope it helps.

**Comment by denis-tingaikin** [comment] 2021-09-28 15:04
We found and fixed a few big issues with stability recently. So probably the problem is already fixed for `latest` images. 
FYI: Soon we'll provide `1.1.0` with these fixes.

So if you will have a time please retest this with latest images and let us know about any problems.

Also logs from nsmgr, forwarders, nsc,nse are welcome!

**Comment by rpiceage** [comment] 2021-09-29 07:49
Hi,
The first try looked OK. There are a number of "context deadline exceeded" errors in NSC logs, but the ping works after upgrade and the nsm-1 interface remained in place.

[forwarder-vpp-5dhh5_logs.txt](https://github.com/networkservicemesh/cmd-nse-icmp-responder/files/7249836/forwarder-vpp-5dhh5_logs.txt)
[forwarder-vpp-6xptm_logs.txt](https://github.com/networkservicemesh/cmd-nse-icmp-responder/files/7249837/forwarder-vpp-6xptm_logs.txt)
[forwarder-vpp-7grzh_logs.txt](https://github.com/networkservicemesh/cmd-nse-icmp-responder/files/7249839/forwarder-vpp-7grzh_logs.txt)
[forwarder-vpp-v2s9x_logs.txt](https://github.com/networkservicemesh/cmd-nse-icmp-responder/files/7249840/forwarder-vpp-v2s9x_logs.txt)
[nsc_logs.txt](https://github.com/networkservicemesh/cmd-nse-icmp-responder/files/7249841/nsc_logs.txt)
[nse_logs.txt](https://github.com/networkservicemesh/cmd-nse-icmp-responder/files/7249842/nse_logs.txt)
[nsmgr-7tp54_logs.txt](https://github.com/networkservicemesh/cmd-nse-icmp-responder/files/7249843/nsmgr-7tp54_logs.txt)
[nsmgr-68z82_logs.txt](https://github.com/networkservicemesh/cmd-nse-icmp-responder/files/7249844/nsmgr-68z82_logs.txt)
[nsmgr-m64jk_logs.txt](https://github.com/networkservicemesh/cmd-nse-icmp-responder/files/7249845/nsmgr-m64jk_logs.txt)
[nsmgr-pnrhz_logs.txt](https://github.com/networkservicemesh/cmd-nse-icmp-responder/files/7249846/nsmgr-pnrhz_logs.txt)
d.

**Comment by denis-tingaikin** [comment] 2021-09-29 15:25
> but the ping works after upgrade and the nsm-1 interface remained in place.

Hm.. Is this equal to your expectation?

**Comment by edwarnicke** [comment] 2021-09-29 15:27
@rpiceage There's a certain amount of 'reconvergence' that happens on upgrade... which can lead to 'context exceeded errors' in the logs.  A common element of 'resiliency' is to continue to deliver the thing you *actually* care about in the face of failure.  The 'context exceeded' errors are telling you various things are failing... but the nsm-1 remaining in place and ping working after upgrade are the 'thing you care about'... correct?

**Comment by rpiceage** [comment] 2021-09-30 09:18
Yes, I agree, the functionality is what matters. However I tested it in our test environment as well with traffic, and there has been errors and connection loss. It is not entirely deterministic.
The versions tested were around 6 days old:

nsmgr=472f18d
registry-memory=f922aee
forwarder-vpp=476e23d
nse-icmp-responder=c785025
nse-icmp-responder-vpp=e1f4bbf

I tried to gather some logs, there were errors in one nsmgr and one forwarder-vpp, and also NSE and NSC.

[forwarder-vpp-88zqv.txt](https://github.com/networkservicemesh/cmd-nse-icmp-responder/files/7258321/forwarder-vpp-88zqv.txt)
[nsc.txt](https://github.com/networkservicemesh/cmd-nse-icmp-responder/files/7258323/nsc.txt)
[nse.txt](https://github.com/networkservicemesh/cmd-nse-icmp-responder/files/7258324/nse.txt)
[nsmgr-5dtc7.txt](https://github.com/networkservicemesh/cmd-nse-icmp-responder/files/7258325/nsmgr-5dtc7.txt)

**Comment by edwarnicke** [comment] 2021-09-30 14:24
@denis-tingaikin Thoughts?

**Comment by denis-tingaikin** [comment] 2021-11-11 16:21
Should be fixed with the latest fixes in sdk.

Could you please re-test it?

**Comment by edwarnicke** [comment] 2021-11-11 16:34
@rpiceage  ^^^^

**Comment by rpiceage** [comment] 2021-11-16 09:17
Re-tested it, still has some problems, but I can't get proper logs because of https://github.com/networkservicemesh/cmd-nsmgr/issues/417

**Comment by denis-tingaikin** [comment] 2021-11-17 17:25
@rpiceage Seems to me networkservicemesh/cmd-nsmgr#417 is fixed. Could you provide logs?

**Comment by denis-tingaikin** [comment] 2021-11-17 22:21
@rpiceage We've fixed the initial problem of this issue that we found in logs in https://github.com/networkservicemesh/cmd-nse-icmp-responder/issues/287#issuecomment-929927332

The problem was fixed in https://github.com/networkservicemesh/sdk/issues/1079

**Comment by denis-tingaikin** [comment] 2021-11-17 22:21
@rpiceage If you found some new problems and this is greate! Let's consider them in separate tickets :)

**Closed** 2021-11-17 22:22 UTC
Labels: bug, stability

**Comment by rpiceage** [comment] 2021-11-19 14:22
Yes, I could verify that the issue is solved, thanks. Upgrade is working now,
